### ISSUE TITLE
NgbdDatepickerPopup

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-jjd#24]
- Le composant ne doit pas être préfixé avec `ngb`, car `ngb` c'est le sélecteur de `ngboostrap`, vous votre sélecteur c'est `app`... comme dans tout vos composants...
- Question ultime comment vous récupérez la valeur (la date) de ce date picker ? Je pense qu'il vous manque un `@Output` pour récupérez cette valeur...

**Comment by JeremyFoucault-SG** [comment]
Composant à supprimer inutile !
