### ISSUE TITLE
FooterComponent

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-jjd#29]
Pas de 
```html 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```
Installer plutôt le packageg npm https://www.npmjs.com/package/font-awesome et importer le css dans votre script `styles.css`

**Comment by ghost** [comment]
I think it's ok :)
